- name: config created
  # Couldn't find a module or role :(
  # Be aware of the k8s certs you use for signing user certs ( like server-ca.crt ).
  # I spent couple of hours to find out the right cert.
  shell:
   |
    kubectl config --kubeconfig={{kubeconfigPath}} set-cluster aws --server=https://{{ansible_host}}:6443 \
    --certificate-authority={{k3sCertPath}}/server-ca.crt --embed-certs=true

    kubectl config --kubeconfig={{kubeconfigPath}} set-credentials {{user}} \
    --client-certificate={{certPath}}/{{user}}.crt --client-key={{certPath}}/{{user}}.pem --embed-certs=true

    kubectl config --kubeconfig={{kubeconfigPath}} set-context aws-cluster --cluster=aws \
     --namespace={{ns}} --user={{user}}

    kubectl config --kubeconfig={{kubeconfigPath}} use-context aws-cluster

