server:
  port: 8081
spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/user_db
    user: postgres
    password: postgres
    locations: classpath:userdb
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
jwt:
  secret: secret
  authTokenExpire: 1200000
  refreshTokenExpire: 30000000