server:
  port: 8081
spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/converter_db
    user: postgres
    password: postgres
    locations: classpath:db
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/converter_db

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none