
server:
  port: 8081
  servlet:
    context-path: /backend/auth
emailVerification:
  link: http://localhost:3000/?token=
  expiration: 1440 #in minutes
spring:
  mail:
    port: 587
    host: smtp.gmail.com
    username: cbrconverter@gmail.com
    password: rqhylbwsgkenzevl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  flyway:
    url: jdbc:postgresql://localhost:5432/auth_db
    user: postgres
    password: postgres
    locations: classpath:authdb
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db
  jpa:

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
jwt:
  secret: secret
  auth.token.expire: 12000000
  refresh.token.expire: 300000000
