
spring:

  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_AUTH_DB}



management:
  endpoints:
    web:
      base-path: /auth
  security:
    enabled: false
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always