apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-historydb-job
spec:
  template:
    metadata:
      labels:
          app: {{ .Values.name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.name }}-historydb
          image: {{ .Values.history.image }}:v1
          imagePullPolicy: Always
          env:
          - name: FLYWAY_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: FLYWAY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: FLYWAY_URL
            value: jdbc:postgresql://cbr-converter:5432/history_db
          command: ["flyway", "migrate"]
