apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-historydb-job
spec:
  template:
    metadata:
      labels:
          app: {{ .Values.name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.name }}-historydb
          image: {{ .Values.history.image }}:{{ .Values.history.tag }}
          imagePullPolicy: Always
          command: ["flyway", "migrate"]
