apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-converterdb-job
spec:
  template:
    metadata:
      labels:
          app: {{ .Values.name }}
    spec:
      restartPolicy: {{ .Values.restart }}
      containers:
        - name: {{ .Values.name }}-converterdb
          image: {{ .Values.converter.image }}:{{ .Values.converter.tag }}
          imagePullPolicy: Always
          env:
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          command: ["flyway", "migrate"]
