apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-historydb-job
  namespace: {{ .Values.global.ns }}

spec:
  template:
    metadata:
      labels:
          app: {{ .Values.name }}
    spec:
      restartPolicy: {{ .Values.restart }}
      containers:
        - name: {{ .Values.name }}-historydb
          image: {{ .Values.history.image }}:v1
          imagePullPolicy: Always
          env:
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: FLYWAY_URL
              value: jdbc:postgresql://cbr-converter:5432/{{ (split "-" .Values.history.image )._1 | replace "db" "_db" }}
          command: ["flyway", "migrate"]
