- name: Create db playbook
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:


  - name: wait for postgres to start
    shell: kubectl get pod postgres-0 --ignore-not-found=true -o json
    retries: 5
    delay: 20
    register: kubectl_get_pods
    until: kubectl_get_pods.stdout|from_json|json_query('status.phase')|unique == ["Running"]
  - name: create db
    kubernetes.core.k8s_exec:
      namespace: default
      pod: postgres-0
      command: "psql -c 'CREATE DATABASE {{ new_db }};'"
    failed_when: False
