version: '3.7'

x-common-variables: &cbr-variables
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  FLYWAY_USER: 'postgres'
  FLYWAY_PASSWORD: 'postgres'
  DB_HOST: 'cbr-converter'
services:
  cbr-converter:
    image: postgres
    container_name: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment: *cbr-variables
    ports:
      - 5432:5432
    networks:
      - cbr-network-backend

  postgres-create-db:
    build:
      context: .
      dockerfile: postgres-createdb/Dockerfile
    container_name:  postgres-create-db-job
    environment:
      - PGPASSWORD=postgres
      - PGHOST=cbr-converter
      - PGUSER=postgres
    command: >
      sh -c "./create-multiple-databases.sh auth_db convert_db history_db"
    depends_on:
      - cbr-converter
    networks:
      - cbr-network-backend
    restart: unless-stopped

  flyway-auth:
    build:
      context: .
      dockerfile: auth-service/flyway/Dockerfile
    container_name: flyway-authdb
    environment:
      <<: *cbr-variables
      FLYWAY_URL: 'jdbc:postgresql://cbr-converter:5432/auth_db'
    command: ["migrate"]
    networks:
      - cbr-network-backend
    depends_on:
      - cbr-converter
    restart: on-failure

  flyway-convert:
    build:
      context: .
      dockerfile: convert-service/flyway/Dockerfile
    container_name: flyway-convertdb
    environment:
      <<: *cbr-variables
      FLYWAY_URL: 'jdbc:postgresql://cbr-converter:5432/convert_db'
    command: [ "migrate" ]
    networks:
      - cbr-network-backend
    depends_on:
      - cbr-converter
    restart: on-failure

  flyway-history:
    build:
      context: .
      dockerfile: history-service/flyway/Dockerfile
    container_name: flyway-historydb
    environment:
      <<: *cbr-variables
      FLYWAY_URL: 'jdbc:postgresql://cbr-converter:5432/history_db'
    command: [ "migrate" ]
    networks:
      - cbr-network-backend
    depends_on:
      - cbr-converter
    restart: on-failure

  auth:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    environment:
      <<: *cbr-variables
      POSTGRES_AUTH_DB: 'auth_db'
    container_name: auth-service
    ports:
      - 8081:8081
    depends_on:
      - cbr-converter
    networks:
      - cbr-network-backend

  convert:
    build:
      context: .
      dockerfile: ./convert-service/Dockerfile
    environment:
      <<: *cbr-variables
      POSTGRES_CONVERT_DB: 'convert_db'
      HISTORY_URL: 'http://history:8083'
    container_name: convert-service
    ports:
      - 8082:8082
    depends_on:
      - cbr-converter
    networks:
      - cbr-network-backend

  history:
    build:
      context: .
      dockerfile: ./history-service/Dockerfile
    environment:
      <<: *cbr-variables
      POSTGRES_HISTORY_DB: 'history_db'
    container_name: history-service
    ports:
      - 8083:8083
    depends_on:
      - cbr-converter
    networks:
      - cbr-network-backend

networks:
  cbr-network-backend:
    name: cbr-network
