version: '3.1'
services:
  flyway:
    container_name: flyway
    build:
      context: .
      dockerfile: ./flyway/Dockerfile
    #Copy is used instead
#    volumes:
#      - ./src/main/resources/db:/flyway/sql
    depends_on:
      - db

  converter:
    container_name: converter
    build:
      ./
    ports:
    - 8080:8080
    depends_on:
      - flyway
    command: bash -c "./wait-for-it.sh db:5432 -t 0 && java -jar /usr/app/converter-0.0.1-SNAPSHOT.jar --spring.profiles.active=docker"
  db:
    build:
      ./postgres
    ports:
      - 5432:5432
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
