version: '3.1'
services:
  flyway:
    container_name: flyway
    build:
      ./flyway
    volumes:
      - ./src/main/resources/db:/flyway/sql
    depends_on:
      - db

  converter:
    container_name: converter
    build:
      ./
    ports:
    - 8080:8080
    depends_on:
      - flyway
  db:
    build:
      ./postgres
    ports:
      - 5432:5432
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #Saves data after container's removal
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data

#volumes:
#  data: { }
