POST http://localhost:8081/auth/registration
Content-Type: application/json

{
    "username":"why1",
    "password":"why1"
}

###
POST http://localhost:8081/auth/login

{
    "username":"why1",
    "password":"why1"
}
###
GET http://localhost:8081/auth/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3aHkxIiwiaXNzIjoiL2F1dGgvbG9naW4iLCJleHAiOjE2Mjk4MzQzMzJ9.Wz5A6TAfw3JlevHb_ibCrab0Y_LJcn325rzTXOIQsZA


###
POST http://localhost:8082/convert/convert
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3aHkxIiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiL2F1dGgvbG9naW4iLCJleHAiOjE2MzkxODU4MTJ9.neuOkNgCvVw86gzf8HOI2oERZ0i7ZYD2V6veFWdJNeE
Content-Type: application/json

{
    "baseCurrency": "USD",
    "quantityToConvert": 20,
    "targetCurrency": "EUR"
}
###
GET http://localhost:8083/history/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3aHkxIiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiL2F1dGgvbG9naW4iLCJleHAiOjE2MzkxODU4MTJ9.neuOkNgCvVw86gzf8HOI2oERZ0i7ZYD2V6veFWdJNeE
