## somehow k3s has traefik installed. We need to remove it
- name: delete traefik
  kubernetes.core.helm:
    kubeconfig: "{{home}}/.kube/config"
    name: traefik
    release_namespace: kube-system
    state: absent
- name: delete traefik-crd
  kubernetes.core.helm:
    kubeconfig: "{{home}}/.kube/config"
    name: traefik-crd
    release_namespace: kube-system
    state: absent

- name: add traefik
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"
- name: install traefik
  kubernetes.core.helm:
    kubeconfig: "{{home}}/.kube/config"
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    state: present
    create_namespace: true
    values_files:
      - "{{manifestCopyFolder}}/traefik.yml.j2"
- name: Apply dashboard
  k8s:
    kubeconfig: "{{home}}/.kube/config"
    state: present
    src: "{{manifestCopyFolder}}/traefik-dashboard.yaml.j2"
