server:
  port: 8083
spring:
  queue: cbr_queue

  flyway:
    url: jdbc:postgresql://localhost:5432/history_db
    user: postgres
    password: postgres
    locations: classpath:historydb
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/history_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
jwt:
  secret: secret
