spring:

  flyway:
    enabled: false
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_HISTORY_DB}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8083
management:
  endpoints:
    web:
      base-path: /history
  security:
    enabled: false
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
