apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name }}-deployment
  namespace: {{ .Values.global.ns }}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name}}
      annotations:
        checksum/config: {{ include (print $.Chart.Home "/templates/cbr-converter-cm.yml") . | sha256sum }}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}:{{.Values.tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.port}}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: cbr-converter-config
          livenessProbe:
            httpGet:
              path: /backend/{{.Values.name}}/health/livenessState
              port: {{.Values.port}}
            initialDelaySeconds: {{.Values.global.initDelay}}
            periodSeconds: {{.Values.global.period}}
          readinessProbe:
            httpGet:
              path: /backend/{{.Values.name}}/health/readinessState
              port: {{.Values.port}}
            initialDelaySeconds: {{.Values.global.initDelay}}
            periodSeconds: {{.Values.global.period}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
  namespace: {{ .Values.global.ns }}

spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}
  ports:
    - port: {{.Values.port}}
      targetPort: {{.Values.port}}
      protocol: TCP
