apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      services:
        - name: history-service
          port: 8083
  tls:
      certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
  tls:
    certResolver: letsencrypt
