apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru")  && PathPrefix("/tls")
      kind: Rule
      services:
        - name: myconverter
          port: 80
  tls:
      certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconverternotls
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru")  && PathPrefix("/notls")
      kind: Rule
      services:
        - name: myconverter
          port: 80
