apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: myconvertertlshistory
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      services:
        - name: history-service
          port: 8083
  tls:
    certResolver: le
    domains:
      - main: "myconverter.woyd.ru"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: myconvertertlsauth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
  tls:
    certResolver: le
    domains:
      - main: "myconverter.woyd.ru"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: myconverternotlsauth
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: myconverternotlsauthip
spec:
  entryPoints:
    - web
  routes:
    - match: Host("34.116.220.96") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconverternotlshistory
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      services:
        - name: history-service
          port: 8083

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`myconverter.woyd.ru`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService