apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru")
      kind: Rule
      services:
        - name: auth
          port: 8081
  tls:
      certResolver: letsencrypt
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru")
      kind: Rule
      services:
        - name: history
          port: 8083
  tls:
    certResolver: letsencrypt