apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: history-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      services:
        - name: history-service
          port: 8083
  tls:
    certResolver: le
    domains:
      - main: "myconverter.woyd.ru"

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: history-notls
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      middlewares:
        - name: test-redirectscheme
      services:
        - name: history-service
          port: 8083

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule

      services:
        - name: auth-service
          port: 8081
  tls:
    certResolver: le
    domains:
      - main: "myconverter.woyd.ru"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-notls
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule
      middlewares:
        - name: test-redirectscheme
      services:
        - name: auth-service
          port: 8081

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: convert-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/convert")
      kind: Rule
      services:
        - name: convert-service
          port: 8082
  tls:
    certResolver: le
    domains:
      - main: "myconverter.woyd.ru"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: convert-notls
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/convert")
      kind: Rule
      middlewares:
        - name: test-redirectscheme
      services:
        - name: convert-service
          port: 8082

