apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertlshistory
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      services:
        - name: history-service
          port: 8083
  tls:
      certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconvertertlsauth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconverternotlsauth
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconverternotlsauthip
spec:
  entryPoints:
    - web
  routes:
    - match: Host("34.116.220.96") && PathPrefix("/auth")
      kind: Rule
      services:
        - name: auth-service
          port: 8081
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myconverternotlshistory
spec:
  entryPoints:
    - web
  routes:
    - match: Host("myconverter.woyd.ru") && PathPrefix("/history")
      kind: Rule
      services:
        - name: history-service
          port: 8083
