podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0
additionalArguments:
  - "--certificatesresolvers.le.acme.httpchallenge=true"
  - "--certificatesresolvers.le.acme.email=cptmutchell@gmail.com"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.le.acme.tlschallenge=true"
  - "--entrypoints.web.address=:80"

  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
#  - "--traefik.http.routers.traefik.priority=1"
#certificatesResolvers:
#  le:
#    acme:
#      caServer: https://acme-v02.api.letsencrypt.org/directory
#      email: cptmutchell@gmail.com
#      storage: /data/acme.json
#      httpChallenge:
#        entryPoint: web
http:
  routers:
    http-catchall:
      rule: hostregexp(`{myconverter.woyd.ru:.+}`)
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  path: /data
  annotations: {}
ports:
  traefik:
    expose: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
  websecure:
    expose: true
    exposedPort: 443
    port: 8443
    protocol: TCP
    tls:
      certResolver: le
      domains:
        - main: myconverter.woyd.ru

      enabled: true


globalArguments: [] # Disable anonymous stat

pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
#ingressClass:
#  enabled: true
#  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml