podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0
additionalArguments:
  - "--certificatesresolvers.le.acme.httpchallenge=true"
  - "--certificatesresolvers.le.acme.email=cptmutchell@gmail.com"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.le.acme.entrypoint=websecure"
#certificatesResolvers:
#  le:
#    acme:
#      caServer: https://acme-v02.api.letsencrypt.org/directory
#      email: cptmutchell@gmail.com
#      storage: /data/acme.json
#      httpChallenge:
#        entryPoint: web

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  path: /data
  annotations: {}
ports:
  traefik:

    expose: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
  websecure:
    expose: true
    exposedPort: 443
    port: 8443
    protocol: TCP
    tls:
      certResolver: le

      enabled: true


globalArguments: [] # Disable anonymous stat

pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
#ingressClass:
#  enabled: true
#  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml