podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0
additionalArguments: []
#  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
#  - "--certificatesresolvers.letsencrypt.acme.email=cptmutchell@gmail.com"
#  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
##  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
#  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
#  - "--certificatesresolvers.letsencrypt.acme.entrypoint=websecure"
certificatesResolvers:
  letsencrypt:
    acme:
      email: cptmutchell@gmail.com
      storage: /data/ache.json
      httpChallenge:
        entryPoint: web

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  path: /data
  annotations: {}
ports:
  traefik:

    expose: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
  websecure:
    expose: true
    exposedPort: 443
    port: 8443
    protocol: TCP
    tls:
      certResolver: letsencrypt

      enabled: true


globalArguments: [] # Disable anonymous stat

pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
#ingressClass:
#  enabled: true
#  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml