podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0
additionalArguments:
#  - "--ping.entrypoint=web"
  - "--certificatesresolvers.letsencrypt.acme.email=cptmutchell@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
#      # Please note that this is the staging Let's Encrypt server.
#      # Once you get things working, you should remove that whole line altogether.
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
initContainers:

  - name: volume-permissions
    image: busybox:1.31.1
    command: ["sh", "-c", "chmod -Rv 600 /data/*"]
    volumeMounts:
      - name: data
        mountPath: /data
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  path: /data
  annotations: {}
ports:
  traefik:
    expose: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
  websecure:
    expose: true
    exposedPort: 443
    port: 8443
    protocol: TCP
    tls:
      certResolver: letsencrypt
      domains:
      - main: myconverter.woyd.ru

      enabled: true
      options: ""


globalArguments: [] # Disable anonymous stat

pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
#ingressClass:
#  enabled: true
#  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml