---
apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth
  namespace: traefik
data:
  users: |
    YWRtaW46JGFwcjEkbk15c3BOTVMkbm5lU0ROYjQ1SEdlM0ZHTkhzSFJqMQoK

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth
