podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0

globalArguments: [] # Disable anonymous stat
ports:
  websecure:
    expose: false
pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
ingressClass:
  enabled: true
  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml