podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0
#additionalArguments:
#  - "--log.level=DEBUG"
#  - "--entrypoints.websecure.http.tls"
#  - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
#  - "--ping"
entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: cptmutchell@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http
globalArguments: [] # Disable anonymous stat
ports:
  websecure:
    expose: false
pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
#ingressClass:
#  enabled: true
#  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml