podDisruptionBudget:
  enabled: true
  minAvailable: 1
rollingUpdate:
  maxUnavailable: 0
#additionalArguments:
#  - "--certificatesresolvers.le.acme.email=cptmutchell@gmail.com"
#  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
#  #- "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
#  - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

#initContainers:
#  - name: volume-permissions
#    image: busybox:1.31.1
#    command: ["sh", "-c", "chmod -Rv 600 /data/*"]
#    volumeMounts:
#      - name: data
#        mountPath: /data
#persistence:
#  enabled: true
#  name: data
#  accessMode: ReadWriteOnce
#  size: 128Mi
#  storageClass: ""
#  path: /data
#  annotations: {}
ports:
  traefik:
    expose: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
#  websecure:
#    expose: true
#    exposedPort: 443
#    port: 8443
#    protocol: TCP
#    tls:
#      certResolver: le
#      domains:
#        - main: myconverter.woyd.ru
#
#      enabled: true


globalArguments: [] # Disable anonymous stat

pilot:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
    labels:


ingressClass:
  enabled: true
  isDefaultClass: true
logs:
  general:
    level: DEBUG
#
#  helm upgrade traefik traefik/traefik
#  --install
#  --create-namespace
#  --namespace traefik
#  --values traefik.yml