
- name: create dirs
  file:
    path: "{{home}}/{{item}}"
    state: directory
  with_items:
    - jenkins
    - jenkins/files
    - jenkins/files/.kube

- name: chmod for volume
  file:
    path: "{{home}}/jenkins/files"
    state: directory
    mode: 0667

- name: copy files
  copy:
    dest: "{{home}}/jenkins"
    src: "{{item}}"
  with_items:
    - Dockerfile
    - jenkins-casc.yaml
    - plugins.txt
    - docker-compose.yml
- name: copy jenkins_config to volume
  copy:
    dest: "{{home}}/jenkins/files/.kube/config"
    src: jenkins_config



- name: docker-compose up --build
  community.docker.docker_compose:
    project_src: "{{home}}/jenkins"
    build: yes
  register: output
- ansible.builtin.debug:
    var: output


