apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/postges-cm.yml") . | sha256sum }}
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 8081
      protocol: TCP
      nodePort: 30001
      targetPort: 8081


