apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: user-db
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/postgres-cm.yml") . | sha256sum }}
      labels:
        app: {{ .Values.name }}
    spec:

      containers:
        - name: cbr-converter-db
          image: {{ .Values.image}}:{{ .Values.tag}}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpass
                  key: PGPASSWORD
            - name: POSTGRES_MULTIPLE_DATABASES
              value: user_db, converter_db,history_db

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-user-db-storage
              subPath: postgres
          readinessProbe:
            failureThreshold: 5
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U {{ .Values.name }} -p {{ .Values.port }}
      volumes:
        - name: postgres-user-db-storage
          persistentVolumeClaim:
            claimName: postgres-user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cbr-converter
spec:
  selector:
    app: {{ .Values.name }}

  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
