apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.jobName }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.jobName }}
          image: {{ .Values.image }}:v1
          imagePullPolicy: Always
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command: ["./create-multiple-databases.sh"]
          args:
            {{  range .Values.args }}
            - {{ . }}
          {{ end }}
