apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-createdb-job
spec:
  template:
    metadata:
      labels:
        app: createdb-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: createdb-job
          image: {{ .Values.image }}:v1
          imagePullPolicy: Always
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command: ["./create-multiple-postgresql-databases.sh"]
          args:
            {{  range .Values.args }}
            - {{ . }}
          {{ end }}
