apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.global.ns }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: postgres-cbr-db
  template:

    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/postgres-cm.yml") . | sha256sum }}
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: cbr-converter-db
          image: postgres:13
          ports:
            - containerPort: {{ .Values.port }}

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/postgresql/data:z
              name: postgres-cbr-db-storage
          readinessProbe:
            failureThreshold: 5
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U {{ .Values.name }} -p {{ .Values.port }}
      volumes:
        - name: postgres-cbr-db-storage
          persistentVolumeClaim:
            claimName: postgres-cbr-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cbr-converter
  namespace: {{ .Values.global.ns }}
spec:
  selector:
    app: {{ .Values.name }}

  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
