
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-createdb-job
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      restartPolicy: OnFailure
      containers:

        - name: {{ .Values.name }}-createdb-job
          image: postgres:11-alpine
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command:
            - su postgres
            - psql
            - -c
            - >
             -U postgres -p postgres -h cbr-converter CREATE DATABASE hhhh;