# This is for example, in real life you'd better create secrets imperatively.
# For example you can get values from jenkins credentials
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: postgres-secret*/}}
{{/*  namespace: {{ .Values.global.ns }}*/}}

{{/*data:*/}}
{{/*  POSTGRES_PASSWORD: cG9zdGdyZXM= #postgres*/}}
{{/*  POSTGRES_USER: cG9zdGdyZXM=*/}}
