
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-createdb-job
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      restartPolicy: OnFailure
      containers:

        - name: {{ .Values.name }}-createdb-job
          securityContext:
            runAsNonRoot: true

          image: postgres:11-alpine
          imagePullPolicy: Always
          env:

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command:
            - psql

            - -c
            - >
             -U postgres -p postgres -h cbr-converter CREATE DATABASE hhhh;