
spring:
  #  flyway:
  #    url: jdbc:postgresql://${USER_DB_HOST}:5432/${POSTGRES_USER_DB}
  #    user: ${POSTGRES_USER}
  #    password: ${POSTGRES_PASSWORD}
  #    locations: classpath:userdb
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_CONVERT_DB}


#jwt:
#  secret: secret
#  authTokenExpire: 1200000
#  refreshTokenExpire: 30000000

management:
  endpoints:
    web:
      base-path: /convert
  security:
    enabled: false
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always