
spring:
  flyway:
    enabled: false
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_CONVERT_DB}

server:
  port: ${CONVERT_PORT}
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  security:
    enabled: false
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always

history.url: ${HISTORY_URL}