
spring:
#  flyway:
#    url: jdbc:postgresql://localhost:5432/converter_db
#    user: postgres
#    password: postgres
#    locations: classpath:converterdb

  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_CONVERTER_DB}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

cbr.url: http://www.cbr.ru/scripts/XML_daily.asp
server:
  port: 8082

management:
  endpoints:
    web:
      base-path: /converter
  security:
    enabled: false
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always