
spring:
  flyway:
    enabled: false
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_CONVERT_DB}

server:
  port: ${CONVERT_PORT}
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  health:
    db:
      enabled: true

  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

history.url: ${HISTORY_URL}
rabbitmq:
  # false - disable rabbit and use restTemplate
  # true - enable rabbit convertAndSend instead of restTemplate
  enable: ${RABBITMQ_ENABLE}
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  exchange: ${RABBITMQ_EXCHANGE}
  queue: ${RABBITMQ_QUEUE}
  routing-key: ${RABBITMQ_ROUTING_KEY}