
spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/converter_db
    user: postgres
    password: postgres
    locations: classpath:converterdb

  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/converter_db

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

cbr.url: http://www.cbr.ru/scripts/XML_daily.asp
server:
  port: 8082
