server:
  port: 8082
spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/convert_db
    user: postgres
    password: postgres
    locations: classpath:convertdb
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/convert_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
jwt:
  secret: secret
  authTokenExpire: 12000000
  refreshTokenExpire: 300000000
cbr.url: http://www.cbr.ru/scripts/XML_daily.asp
