apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  serviceName: user-db
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/postgres-cm.yml") . | sha256sum }}
      labels:
        app: {{ .Values.postgres.name }}
    spec:

      containers:

        - name: cbr-converter-db
          image: cptmutchell/postgres-multidb:v1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_MULTIPLE_DATABASES
              value: user_db, converter_db,history_db

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-user-db-storage
         #     subPath: postgres
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U {{ .Values.postgres.name }} -p 5432
      volumes:
        - name: postgres-user-db-storage
          persistentVolumeClaim:
            claimName: postgres-user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cbr-converter
spec:
  selector:
    app: {{ .Values.postgres.name }}

  ports:
    - port: 5432
      targetPort: 5432
